# Generated by Django 3.2.12 on 2022-04-19 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['destination_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_date', models.DateField()),
            ],
            options={
                'ordering': ['travelproduct', 'staff', 'order_id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['order', 'customer'],
            },
        ),
        migrations.CreateModel(
            name='Paymethod',
            fields=[
                ('paymethod_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['payment_method'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_position', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'job_position'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Travelproduct',
            fields=[
                ('travelproduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('travelproduct_name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travelproducts', to='travelsale.destination')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travelproducts', to='travelsale.type')),
            ],
            options={
                'ordering': ['travelproduct_name', 'type', 'destination'],
            },
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'job_position'), name='staff'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='travelsale.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='travelsale.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='travelsale.staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='travelproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='travelsale.travelproduct'),
        ),
        migrations.AddConstraint(
            model_name='travelproduct',
            constraint=models.UniqueConstraint(fields=('travelproduct_name', 'type', 'destination'), name='unique_travelproduct'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('order', 'customer'), name='unique_payment'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('travelproduct', 'staff', 'order_id'), name='unique_order'),
        ),
    ]
