# Generated by Django 3.2.13 on 2022-04-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelsale', '0002_auto_20220419_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='travel_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='travelsale.order', unique=True),
        ),
    ]
